title: Sentra Documentation
description: Official documentation for the Sentra Programming Language - A security-focused programming language with built-in networking capabilities

# GitHub Pages theme
remote_theme: just-the-docs/just-the-docs@v0.10.0

# Site settings  
url: https://sentra-language.github.io
# No baseurl needed for organization site

# Theme configuration
color_scheme: light
search_enabled: true

# Syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: javascript
    span:
      line_numbers: false
    block:
      line_numbers: false

aux_links:
  "GitHub Repository": "https://github.com/sentra-language/sentra"
  "Download Latest": "https://github.com/sentra-language/sentra/releases"

# Footer content
footer_content: "Copyright &copy; 2025 Sentra Language. Distributed under the <a href=\"https://github.com/sentra-language/sentra/blob/main/LICENSE\">MIT License</a>."

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap